### ISSUE TITLE
quick look stopped to fire within page name since 5/16

### ISSUE THREAD

**Issue by laura-mao** [saksdirect/saks-site-catalyst#1]
When clicking quick look, the page name used to be saks.com:**quicklook**:gucci:gg leather belt, but now it fires as saks.com:gucci:gg leather belt.

**Comment by fiftyfactorauthentication** [comment]
@laura-mao you've posted this in the wrong repo. https://github.com/saksdirect/saks-signal is the correct repo for data binding issues.
