### ISSUE TITLE
Time Format in eVar8 Doesn't Match Production

### ISSUE THREAD

**Issue by laura-mao** [saksdirect/saks-site-catalyst#10]
I think that was me changed the format for a project, please change it back to match live site.

**Comment by fiftyfactorauthentication** [comment]
> I think that was me changed the format for a project

I'm not sure what that means, please try to use clearer language in the future.

**Comment by fiftyfactorauthentication** [comment]
Original s_code code:

```js
  if (pageData.site.is_production == 'true') {
    s.eVar8 = s.getTimeParting('f', '-5');
  }
  else if (pageData.site.is_production == 'false') {
    s.eVar8 = s.getSaksTime();
  }
```

New code in this library:

```js
  if (pageData.site.is_production === 'true') {
    visitTime = app.getTimeParting('f', '-5');
  }
  else if (pageData.site.is_production === 'false') {
    visitTime = app.getSaksTime();
  }

  evar(8, visitTime);
```

The code is identical for all intents and purposes. As such, the time formatting will be different from production to qa. Please note this. If you'd like time formatting to be the same regardless of whether you're on production or qa, please specify that.
