### ISSUE TITLE
Incorrect Page Name on Custom Array

### ISSUE THREAD

**Issue by laura-mao** [saksdirect/saks-site-catalyst#11]
E.g. on this custom array - http://www.saksfifthavenue.com/Valentino-Fall-Editorial/shop/_/N-52kgcl/Ne-52iqfl?sre=06062017vlntnd

page name used to be "saks.com:custom:valentinofall2017editorial" but now is "saks.com:valentinofall2017editorial:custom".

**Comment by fiftyfactorauthentication** [comment]
@laura-mao you've posted this in the wrong repo. https://github.com/saksdirect/saks-signal is the correct repo for data binding issues.
