### ISSUE TITLE
Increased Server Call on Homepage

### ISSUE THREAD

**Issue by laura-mao** [saksdirect/saks-site-catalyst#14]
### Please Briefly Describe the Issue
When I went right to the homepage, I saw 3 server calls one after the other:

Call 1: page view of home page, with a v0 value of 'qa.saks.com'
Call 2: custom link call that sets event32 (email signup start) - I did see the overlay so this is good
Call 3: page view call with pageName "saks.com" and c1 "<undefined>" - I'm not sure where this is coming from or what it's for, but it shouldn't be there.

I don't think the 3rd call should be there. On the first call, I think the reason for the wrong channel (v0) is that the value of s.linkInternalFilters is wrong. This is what it's being set to:

"javascript:,saksfifthavenue.com,sakcom,richrelevance.com,paypal.com,checkout.fiftyone.com,paypalcomwww.qa.saks.com"

That missing comma will cause problems both with paypal and the QA site.

### Please add all that apply

You may leave inapplicable fields empty.

* URL of Affected Page:http://www.qa.saks.com/Entry.jsp
* eVar Number:
* sProp Number:
* event Number:
* Expected Value:
* Actual Value:

### Please check [x] all that apply

- [ ] eVar Value is Incorrect  
- [ ] sProp Value is Incorrect  
- [ ] event not added to `s.events`

### Steps to Reproduce

1. Open an incognito window to start a fresh session
2. Open Network tab and filter by "b/ss"
3. Go to Saks STQA site homepage - http://www.qa.saks.com

**Comment by shellscape** [comment]
@laura-mao here's the original code, from the signal s_code file: https://github.com/saksdirect/saks-site-catalyst/blob/master/legacy/script.js#L11

The original code doesn't have a comma between `paypalcom` and the document hostname. I'd also like to point out that `paypalcom` is missing a period between `paypal` and `com`.

Please specify if you're requesting that a comma is inserted there.

**Comment by laura-mao** [comment]
Yes - it should say "paypal.com" and have a comma afterwards, so it will be comma-separated from the current domain.
