### ISSUE TITLE
prop21 Incorrect Value

### ISSUE THREAD

**Issue by michellemyer** [saksdirect/saks-site-catalyst#15]
### Please Briefly Describe the Issue
Searches with 0 results are no longer being returned with “null” as the prefix for prop21

### Please add all that apply

* URL of Affected Page:  (example) https://www.saksfifthavenue.com/search/EndecaSearch.jsp?bmForm=header-search&bmFormID=lVSv0yQ&bmUID=lVSv0yR&bmIsForm=true&bmPrevTemplate=%2FEntry.jsp&bmArch=bmForm&bmForm=endeca_search_form_one&bmHidden=submit-search&submit-search=&bmArch=bmSingle&bmSingle=N_Dim&bmHidden=N_Dim&N_Dim=0&bmArch=bmHidden&bmHidden=Ntk&bmHidden=Ntk&Ntk=Entire+Site&bmArch=bmHidden&bmHidden=Ntx&bmHidden=Ntx&Ntx=mode%2Bmatchpartialmax&bmHidden=Ntt&Ntt=asdfsd&bmText=SearchString&SearchString=asdfsd

* eVar Number:
* sProp Number: 21
* event Number:
* Expected Value: (example) null:abcdefg
* Actual Value: (example) abcdefg

### Please check [x] all that apply

- [ ] eVar Value is Incorrect  
- [x] sProp Value is Incorrect  
- [ ] event not added to `s.events`

### Steps to Reproduce

1. Type a nonsense string of letters into the search box on saks.com
2.  A ‘No results were found’ page appears
3.  This page has the incorrect value firing for prop21

**Comment by fiftyfactorauthentication** [comment]
@michellemyer what's the type (string or number) value of `sProp24` (the result count) in this instance? The value of `sProp24` determines whether or not `'null:'` is prepended to `sProp21` (the search term) as can be seen here https://github.com/saksdirect/saks-site-catalyst/blob/master/src/search.js#L15

**Comment by michellemyer** [comment]
@fiftyfactorauthentication - I'm seeing sProp24 as 0 for these null terms
