### ISSUE TITLE
 double colon(:) in page name on DLP

### ISSUE THREAD

**Issue by laura-mao** [saksdirect/saks-site-catalyst#2]
E.g. http://www.saksfifthavenue.com/main/WorldOfDesigner.jsp?FOLDER%3C%3Efolder_id=2534374305092117&PRODUCT%3C%3Eprd_id=845524446958526&bmUID=lO7CmtF.

Page name is used to be saks.com:brand:designer:dior:main, but now saks.com:brand:designer::dior:main

**Comment by fiftyfactorauthentication** [comment]
@laura-mao you've posted this in the wrong repo. https://github.com/saksdirect/saks-signal is the correct repo for data binding issues.
