### ISSUE TITLE
RawGit is phasing out

### ISSUE THREAD

**Issue by gurghet** [saksdirect/saks-site-catalyst#29]
https://rawgit.com/

It seems we serve this via rawgit which is phasing out in October 2019. In case we still use it next year we will need to migrate the cdn.
![screenshot 2018-10-15 at 10 34 58](https://user-images.githubusercontent.com/420735/46942793-fb3aa900-d065-11e8-979c-2d2b42d48762.png)

**Comment by track0x1** [comment]
I just switched to `jsdelivr` for the time being.
