### ISSUE TITLE
eVar36 not fire

### ISSUE THREAD

**Issue by laura-mao** [saksdirect/saks-site-catalyst#5]
eVar36= Top level marketing channel.

eVar36 should fire on landing page, for example eVar36 should equal "search" on this landing page: http://www.qa.saks.com/Entry.jsp?site_refer=360i

**Comment by fiftyfactorauthentication** [comment]
@laura-mao eVars do not "fire." Rather, their values are assigned. Please use the correct terminology moving forward.

Note that this eVar value is only set once, after which a cookie is created that instructs Site Catalyst not to set this value again until the cookie expires.

**Comment by laura-mao** [comment]
"fire" is the right terminology. We do use "fire" instead of assign in Analytics. 

Thanks for all the comments, I will take a look at all issues.

**Comment by fiftyfactorauthentication** [comment]
Events fire. Variables and Properties are assigned. Please use the correct terminology when reporting issues, as guided here.
