### ISSUE TITLE
Missing Add to Bag event on Quick Look

### ISSUE THREAD

**Issue by laura-mao** [saksdirect/saks-site-catalyst#8]
I don't see cart adds tracking at all on quick looks (only on PDPs)

**Comment by fiftyfactorauthentication** [comment]
@laura-mao you're missing useful information that would allow us to triage this. Please provide URL to reproduce, steps to reproduce, expected values, actual values.

**Comment by fiftyfactorauthentication** [comment]
The code within this repo is not responsible for triggering quick look or add to bag events. 

No part of this element is targeted in this library:

```html
<button class="sfa-button transactional medium js-action-button">ADD TO BAG</button>
```

Please consult the Signal configuration, or contact the appropriate engineering team.
